.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching D_004ADE54

dlabel D_004ADE54
    /* 2ADE54 004ADE54 FFFFFFFF */ .word 0xFFFFFFFF
    /* 2ADE58 004ADE58 00000000 */ .word 0x00000000
enddlabel D_004ADE54
