.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching D_004ADE68

dlabel D_004ADE68
    /* 2ADE68 004ADE68 00000000 */ .word 0x00000000
    /* 2ADE6C 004ADE6C 00000000 */ .word 0x00000000
enddlabel D_004ADE68
