.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.40.0 */

nonmatching D_004ADE5C

dlabel D_004ADE5C
    /* 2ADE5C 004ADE5C FFFFFFFF */ .word 0xFFFFFFFF
enddlabel D_004ADE5C

nonmatching D_004ADE60

dlabel D_004ADE60
    /* 2ADE60 004ADE60 00000000 */ .word 0x00000000
    /* 2ADE64 004ADE64 00000000 */ .word 0x00000000
enddlabel D_004ADE60
