#include "common.h"

INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkInit);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkReset);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkTerminate);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkSize);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkCnt);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkRef);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkEnd);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkOpenUpkCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkCloseUpkCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkOpenDirectCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkCloseDirectCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkOpenGifTag);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkCloseGifTag);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkReserve);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAlign);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddDataN);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddUpkData128);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddGsData);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddGsAD);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkRefLoadImage);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkOpenDirectHLCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkCloseDirectHLCode);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddUpkData128N);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddDirectDataN);
INCLUDE_ASM("asm/nonmatchings/sceVif1Pk", sceVif1PkAddGsPacked);
